[package]
name = "my-hours"
version = "0.1.0"
edition = "2018"
authors = ["Joni Hasanen <joni@hasanen.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
config = "0.11"
directories-next = "2.0"