[package]
name = "my-hours"
version = "0.1.0"
edition = "2018"
authors = ["Joni Hasanen <joni@pieceofcode.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
directories-next = "2.0"
read_input = "0.8"
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
tui = "0.16"
termion = "1.5"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
prettytable-rs = "0.8"