name: Rust build & tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://lpenz/ghaction-rust-coverage:0.5.0
      - uses: coverallsapp/github-action@v1.1.2
        with:
          dependencies_debian: pkg-config
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./lcov.info